name: Deploy to Production

on:
  push:
    branches: [main, master]  # Adjust these to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger deployment webhook
        run: |
          echo "Triggering deployment webhook..."
          curl -X POST https://webhook.bn-java.awssam.me/ \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -H "X-Hub-Signature-256: sha256=$(echo -n "${{ github.event.after }}${{ secrets.SECRETSPRING }}" | openssl dgst -sha256 -hex | sed 's/^.* //')" \
            -d '{
              "ref": "refs/heads/${{ github.ref_name }}",
              "repository": {
                "full_name": "${{ github.repository }}",
                "default_branch": "${{ github.event.repository.default_branch }}"
              },
              "after": "${{ github.event.after }}"
            }'
          
      - name: Verify deployment status
        run: |
          # Add a small delay to allow webhook processing
          sleep 5
          echo "Checking if deployment was triggered successfully..."
          # Use curl to check the status of your application
          # Adjust the URL to match your application's health check endpoint
          curl -s -o /dev/null -w "%{http_code}" https://bn-java.awssam.me/ || echo "Site might still be deploying"
